// Generates docs/API.md from the route table and zod schemas in packages/contracts,
// so the documentation cannot drift from the code.
import { writeFileSync } from 'node:fs';
import { z } from '../packages/contracts/node_modules/zod/index.js';
import { ExternalJobCallback, ExternalJobRequest, ROUTES, RunEvent } from '../packages/contracts/src/index';

const schema = (s: z.ZodType) =>
  '```json\n' + JSON.stringify(z.toJSONSchema(s, { unrepresentable: 'any', io: 'input' }), null, 2) + '\n```';
const byFeature = new Map<string, typeof ROUTES>();
for (const r of ROUTES) byFeature.set(r.feature, [...(byFeature.get(r.feature) ?? []), r]);

let md = `# Annie 3D API\n\nGenerated by \`scripts/gen-api-doc.ts\` from \`packages/contracts\`. Do not edit by hand.\n\n`;
md += `Base URL: same origin as the app. JSON everywhere. Auth: Better Auth session cookie. Errors: \`{ "error": { "code", "message", "details?" } }\` with codes \`bad_request, unauthenticated, forbidden, not_found, conflict, rate_limited, insufficient_credits, sign_in_required, payload_too_large, unsupported_media, internal\`.\n\n`;
md += `Idempotency: op batches (\`opId\`), runs, edits and exports (\`idempotencyKey\`), payment events (provider event id). Retrying with the same key returns the original result.\n\n`;
md += `## Route index\n\n| Method | Path | Auth | Feature | Summary |\n| --- | --- | --- | --- | --- |\n`;
for (const r of ROUTES) md += `| ${r.method} | \`${r.path}\` | ${r.auth} | ${r.feature} | ${r.summary} |\n`;
for (const [feature, routes] of byFeature) {
  md += `\n## ${feature}\n`;
  for (const r of routes) {
    md += `\n### ${r.method} \`${r.path}\`\n\n${r.summary}. Auth: ${r.auth}.\n`;
    if (r.body) md += `\nRequest body:\n\n${schema(r.body)}\n`;
    if (r.response) md += `\nResponse:\n\n${schema(r.response)}\n`;
  }
}
md += `\n## Run events (WebSocket \`/api/runs/:runId/events?after=<seq>\`)\n\n${schema(RunEvent)}\n`;
md += `\n## External Engine Protocol v1 (plug point for agents)\n\nAnnie 3D → engine: \`POST {engineBaseUrl}/v1/jobs\`\n\n${schema(ExternalJobRequest)}\n\nEngine → Annie 3D: \`POST {callbackUrl}\` with header \`x-annie3d-signature: t=<unix>,v1=<hex HMAC-SHA256(secret, t + "." + rawBody)>\`\n\n${schema(ExternalJobCallback)}\n`;
writeFileSync('docs/API.md', md);
console.log(`docs/API.md: ${ROUTES.length} routes`);
