// Landing-page media from the product's own sample outputs (fixtures/out, generated by
// fixtures/generate.mjs): renders into apps/site/src/assets/media (WebP, through astro:assets) and
// the 9:16 ad videos into apps/site/public/media. fixtures/out is not in git, so the results are
// committed. Usage: node scripts/site-media.mjs
import { copyFileSync, existsSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';

// sharp comes with Astro (the site's image pipeline); no extra dependency at the root.
const fromSite = createRequire(new URL('../apps/site/package.json', import.meta.url));
const sharp = createRequire(fromSite.resolve('astro/package.json'))('sharp');

const SRC = 'fixtures/out';
const IMG = 'apps/site/src/assets/media';
const VID = 'apps/site/public/media';
if (!existsSync(SRC)) throw new Error('Generate the fixtures first: node fixtures/generate.mjs');
mkdirSync(IMG, { recursive: true });
mkdirSync(VID, { recursive: true });

const PRODUCTS = ['serum', 'headphones', 'ring'];
// Square crops around the product (renders leave a wide margin), 1024 px.
const SQUARE = [
  'photo',
  'stage',
  'packshot_three_quarter',
  'packshot_front',
  'packshot_top',
  'packshot_detail',
];
for (const p of PRODUCTS) {
  for (const k of SQUARE) {
    const src = `${SRC}/${p}/${k}.png`;
    if (!existsSync(src)) continue;
    const { width, height } = await sharp(src).metadata();
    const side = Math.round(Math.min(width, height) * 0.78);
    const info = await sharp(src)
      .extract({
        left: Math.round((width - side) / 2),
        top: Math.round((height - side) / 2),
        width: side,
        height: side,
      })
      .resize(1024, 1024)
      .webp({ quality: 84 })
      .toFile(`${IMG}/${p}-${k.replace(/_/g, '-')}.webp`);
    console.log(`${p}/${k}: ${Math.round(info.size / 1024)} KB`);
  }
  copyFileSync(`${SRC}/${p}/ad_9x16.mp4`, `${VID}/${p}-ad-9x16.mp4`);
  await sharp(`${SRC}/${p}/ad_poster_540.webp`).webp({ quality: 82 }).toFile(`${IMG}/${p}-ad-poster.webp`);
  console.log(`${p}: ad video and poster`);
}
